### ISSUE TITLE
Have you

### ISSUE THREAD

**Issue by davidecampello** [hideokamoto/ionic-angular-scully#10]
Hi @hideokamoto! I've seen your website and it look like a ionic app with scully rendering.
I'm looging to make Ionic work with scully but I'm stopped by some problems like the side menu that's not working.
Have you found a solution to make it work?
Thanks!
Davide

**Comment by hideokamoto** [comment]
Unfortunately,mywebsite is made by Ionic with Next.js.
The repo is efor practice.

**Comment by davidecampello** [comment]
No problem, thank you!
